import "./globals.css";
import { Sora } from "next/font/google";
import Navbar from "../components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { DineMarketContextProvider } from "./context/DineContext";
import Footer from "@/components/Footer";

const sora = Sora({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "800"],
});

export const metadata = {
  title: "Dine Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <DineMarketContextProvider>
        <html lang="en">
          <body className={`${sora.className} overflow-x-hidden bg-white`}>
            <div className="flex  min-h-screen flex-col">
              <Navbar />
              <div className="flex justify-center mt-14  py-4 md:mt-[88px] md:py-6 lg:mt-[110px]">
                {children}
              </div>
              <Footer/>
            </div>
          </body>
        </html>
      </DineMarketContextProvider>
    </ClerkProvider>
  );
}
